add error handling for non-200 HTTP response

diff --git a/.github/workflows/imf-who-covid-19-vaccine-supply-tracker.yml b/.github/workflows/imf-who-covid-19-vaccine-supply-tracker.yml
--- a/.github/workflows/imf-who-covid-19-vaccine-supply-tracker.yml
+++ b/.github/workflows/imf-who-covid-19-vaccine-supply-tracker.yml
@@ -21,7 +21,14 @@ jobs:
           CURRENTDATESTRING=$(date +"%Y-%m-%d")
           NEWFILENAME="data/imf-who/imf-who-vaccine-supply-tracker-${CURRENTDATESTRING}.xlsx"
           STATUS=$(curl -s -S -o ${NEWFILENAME} -w '%{http_code}' "https://www.imf.org/en/Topics/imf-and-covid19/-/media/Files/Topics/COVID/IMF-WHO/imf-who-covid-19-vaccine-supply-tracker.ashx")
-      
+          if [ $STATUS -eq 200 ]; then
+            echo "downloaded file"
+          else
+            echo "error code $STATUS downloading file"
+            rm -rf ${NEWFILENAME}
+            exit 1
+          fi
+
       - name: add latest file for commit
         run: git add ${NEWFILENAME}
 
